## Лабораторная работа 1: Алгоритмы разложения матриц. PCA.
_Команда i_ <br>
_Фамилия 1, Фамилия 2, Фамилия 3, Фамилия 4_
### 1. Метод главных компонент
##### Cингулярное матричные разложения

In [105]:
import numpy as np
from math import *
A = np.array([[2.0, 1.0, 0.7, 0.5, 0.4],
              [1.0, 0.6, 0.5, 0.4, 0.3],
              [0.7, 0.5, 0.4, 0.3, 0.2],
              [0.5, 0.4, 0.3, 0.2, 0.2],
              [0.4, 0.3, 0.2, 0.1, 0.2],
              [3.0, 5.0, 0.3, 0.2, 0.8],
              [5.0, 1.2, 0.9, 0.5, 3.5]])

def QR_Decomposition(A):
    n, m = A.shape # get the shape of A
    Q = np.empty((n, n)) # initialize matrix Q
    v = np.empty((n, n)) # initialize matrix u

    v[:, 0] = A[:, 0]
    Q[:, 0] = v[:, 0] / np.linalg.norm(v[:, 0])

    for i in range(1, m):
        v[:, i] = A[:, i]
        for j in range(i):
            v[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j] # get each u vector
        Q[:, i] = v[:, i] / np.linalg.norm(v[:, i]) # compute each e vetor

    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j] @ Q[:, i]

    return Q, R

a = A @ A.T
b = A.T @ A
Q, R = QR_Decomposition(a)
Q1, R1 = QR_Decomposition(b)
left = Q
right = Q1
for i in range(10):
    S = R1 @ Q1
    P = R @ Q
    Q, R = QR_Decomposition(P)
    Q1, R1 = QR_Decomposition(S)
    left = left @ Q
    right = right @ Q1
right = right.T
singular_values = list(map(lambda x: round(sqrt(x), 4), np.diag(R)[:min(A.shape)]))


print('сингулярные числа матрицы А'.upper())    
print(f'нумпаевская наработка: \n{np.linalg.svd(A)[1].round(4)}')
print(f'собственная наработка: \n{singular_values}')
print()
print('левая сингулярная матрица'.upper())
print(f'нумпаевская наработка: \n{np.linalg.svd(A)[0].round(3)}')
print(f'собственная наработка: \n{left.round(3)}')
print()
print('правая сингулярная матрица'.upper())
print(f'нумпаевская наработка: \n{np.linalg.svd(A)[2].round(3)}')
print(f'собственная наработка: \n{right.round(3)}')
print()

opt = sum(singular_values[:3]) / sum(singular_values)

print(f'sigmas%: {round(opt * 100, 2)}%')
for i in singular_values:
    print(f'sig {i}: {round(i / sum(singular_values) * 100, 2)}%')
print()
print(f'СПЕКТРАЛЬНОЕ РАЗЛОЖЕНИЕ (A @ A.T) \n{(left @ np.diag(np.diag(R)) @ left.T).round(3)}')

СИНГУЛЯРНЫЕ ЧИСЛА МАТРИЦЫ А
нумпаевская наработка: 
[8.3724 3.6024 1.0359 0.2831 0.047 ]
собственная наработка: 
[8.3724, 3.6027, 1.0361, 0.2831, 0.0681]

ЛЕВАЯ СИНГУЛЯРНАЯ МАТРИЦА
нумпаевская наработка: 
[[-0.275 -0.029  0.711 -0.62  -0.17   0.    -0.064]
 [-0.153 -0.012  0.446  0.394  0.565 -0.469  0.29 ]
 [-0.112  0.009  0.345  0.422  0.068  0.827  0.041]
 [-0.086  0.008  0.211  0.449 -0.338 -0.265 -0.75 ]
 [-0.068 -0.001  0.098  0.281 -0.73  -0.163  0.59 ]
 [-0.626  0.749 -0.216 -0.011  0.025  0.     0.001]
 [-0.696 -0.661 -0.276  0.018  0.023  0.017 -0.011]]
собственная наработка: 
[[ 0.275 -0.032 -0.713 -0.612  0.198  0.012  0.02 ]
 [ 0.153 -0.004 -0.438  0.368 -0.642 -0.029 -0.049]
 [ 0.113  0.01  -0.344  0.419 -0.088 -0.004 -0.006]
 [ 0.085  0.003 -0.216  0.465  0.365  0.017  0.029]
 [ 0.067 -0.012 -0.108  0.315  0.806  0.038  0.063]
 [ 0.626  0.75   0.216 -0.013 -0.024 -0.002 -0.004]
 [ 0.696 -0.661  0.277  0.017 -0.025 -0.002 -0.003]]

ПРАВАЯ СИНГУЛЯРНАЯ МАТРИЦА
нумпаевская н

##### Представление набора данных

##### Применение метода сингулярного разложения на данных

##### Преимущества и недостатки применения сингулярного и спектрального разложения к задачам PCA

##### Определение числа компонент, визуализация данных, анализ полученных компонент

##### Дополнительное задание

### 2. Kernel PCA

##### Представление набора данных

##### Реализация методов вычисления матрицы для различных ядер  и её последующего спектрального разложения

##### Сравнительный анализ применения PCA и Kernel PCA